use_frameworks!

target 'HTFlipCard_Example' do
  pod 'HTFlipCard', :path => '../'
  pod 'HTUIExtensions'

  target 'HTFlipCard_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
